### ISSUE TITLE
Error when retrieving Universal data 

### ISSUE THREAD

**Issue by georgereason** [cubehouse/wdwJS#19]
I am currently pulling Universal Data regularly throughout the day for a project. The following error has appeared twice in the past two weeks of running the collection. 

Looks like it is a problem when getting the information from the cache.

`/var/app/current/node_modules/wdwjs/Universal/UniversalBase.js:49
      for (var i = 0, ride; ride = self.poi_data.Rides[i++];) {
                                                ^

TypeError: Cannot read property 'Rides' of undefined
    at /var/app/current/node_modules/wdwjs/Universal/UniversalBase.js:49:49
    at /var/app/current/node_modules/wdwjs/Universal/UniversalBase.js:321:16
    at Request._callback (/var/app/current/node_modules/wdwjs/Universal/UniversalBase.js:296:14)
    at Request.self.callback (/var/app/current/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/app/current/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/app/current/node_modules/request/request.js:963:12)
`

**Comment by cubehouse** [comment]
Heya, I'm curious why data wasn't returned, and a successful status code was returned.

If you could make a pull request with the additional check, that would be appreciated. Otherwise I'm not able to get to my computer for a little while, but can still check and merge pull requests on my mobile.

**Comment by georgereason** [comment]
Added Pull Request #20

**Comment by cubehouse** [comment]
Published to npm as 3.0.9
